package com.webapp.fakepeople.repository;

public class Names {
    public static final String[] lastNameBeginnings = new String[]{
            "Nord",
            "Sør",
            "Øst",
            "Vest",
            "Sten",
            "Lyng",
            "Bol",
            "Ryng",
            "Sol",
            "Tei",
            "Ris",
            "Lille",
            "Store",
            "Høy",
            "Lav",
            "Vill",
            "Skje",
            "Skredde",
            "Val",
            "Hald",
    };
    public static final String[] lastNameEndings = new String[]{
            "berg",
            "vik",
            "sand",
            "stad",
            "borg",
            "sæther",
            "vang",
            "heim",
            "bø",
            "land",
            "by",
            "tvedt",
            "hei",
            "my",
            "haug",
            "foss",
            "fjell",
            "skog",
            "li",
            "vann",
            "myr",
            "dane"
    };

    public static final String[] maleNames = new String[]{
            "Markus",
            "Mathias",
            "Kristian",
            "Jonas",
            "Andreas",
            "Alexander",
            "Martin",
            "Sander",
            "Daniel",
            "Magnus",
            "Henrik",
            "Tobias",
            "Kristoffer",
            "Emil",
            "Adrian",
            "Sebastian",
            "Marius",
            "Elias",
            "Fredrik",
            "Thomas",
    };

    public static final String[] femaleNames = new String[]{
            "Emma",
            "Sara",
            "Thea",
            "Ida",
            "Julie",
            "Nora",
            "Emilie",
            "Ingrid",
            "Hanna",
            "Maria",
            "Sofie",
            "Anna",
            "Malin",
            "Amalie",
            "Vilde",
            "Frida",
            "Andrea",
            "Tuva",
            "Victoria",
            "Mia",
    };

    public static final String[] emailProviderNames = new String[]{
            "gmail",
            "hotmail",
            "outlook",
            "icloud",
            "yahoo",
    };
}
